services:
  - name: js-app
    type: web
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: PORT
        value: 3000

  - name: python-app
    type: web
    buildCommand: pip install -r requirements.txt
    startCommand: python TEST_NLP.py
    envVars:
      - key: PORT
        value: 5000
